/**
 * Generated by orval + scripts/restructure-api.ts.
 * Do not edit manually — re-run `pnpm api:generate`.
 */

import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from "@tanstack/react-query";
import { useMutation } from "@tanstack/react-query";
import type { SecondParameter } from "@/api/common/query-helpers";
import type { ErrorType, orvalApiClient } from "@/api/orval-mutator";
import { postReissue as reissue } from "../api/postReissue";

export const getReissueMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof reissue>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof orvalApiClient>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof reissue>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["reissue"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof reissue>>,
    void
  > = () => {
    return reissue(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ReissueMutationResult = NonNullable<
  Awaited<ReturnType<typeof reissue>>
>;

export type ReissueMutationError = ErrorType<unknown>;

export const usePostReissue = <TError = ErrorType<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof reissue>>,
      TError,
      void,
      TContext
    >;
    request?: SecondParameter<typeof orvalApiClient>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof reissue>>,
  TError,
  void,
  TContext
> => {
  return useMutation(getReissueMutationOptions(options), queryClient);
};
