/**
 * Generated by orval + scripts/restructure-api.ts.
 * Do not edit manually — re-run `pnpm api:generate`.
 */

import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { useQuery } from "@tanstack/react-query";
import type { SecondParameter } from "@/api/common/query-helpers";
import { withQueryKey } from "@/api/common/query-helpers";
import type { ErrorType, orvalApiClient } from "@/api/orval-mutator";
import { getMyPollList as myPollList } from "../api/getMyPollList";
import type { GetMyPollListRequest as MyPollListParams } from "../types/GetMyPollListRequest";

export const getMyPollListQueryKey = (params?: MyPollListParams) => {
  return [`/api/users/polls/my`, ...(params ? [params] : [])] as const;
};

export const getMyPollListQueryOptions = <
  TData = Awaited<ReturnType<typeof myPollList>>,
  TError = ErrorType<unknown>,
>(
  params: MyPollListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof myPollList>>, TError, TData>
    >;
    request?: SecondParameter<typeof orvalApiClient>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getMyPollListQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof myPollList>>> = ({
    signal,
  }) => myPollList(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof myPollList>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type MyPollListQueryResult = NonNullable<
  Awaited<ReturnType<typeof myPollList>>
>;
export type MyPollListQueryError = ErrorType<unknown>;

export function useGetMyPollList<
  TData = Awaited<ReturnType<typeof myPollList>>,
  TError = ErrorType<unknown>,
>(
  params: MyPollListParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof myPollList>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof myPollList>>,
          TError,
          Awaited<ReturnType<typeof myPollList>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof orvalApiClient>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMyPollList<
  TData = Awaited<ReturnType<typeof myPollList>>,
  TError = ErrorType<unknown>,
>(
  params: MyPollListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof myPollList>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof myPollList>>,
          TError,
          Awaited<ReturnType<typeof myPollList>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof orvalApiClient>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMyPollList<
  TData = Awaited<ReturnType<typeof myPollList>>,
  TError = ErrorType<unknown>,
>(
  params: MyPollListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof myPollList>>, TError, TData>
    >;
    request?: SecondParameter<typeof orvalApiClient>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetMyPollList<
  TData = Awaited<ReturnType<typeof myPollList>>,
  TError = ErrorType<unknown>,
>(
  params: MyPollListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof myPollList>>, TError, TData>
    >;
    request?: SecondParameter<typeof orvalApiClient>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getMyPollListQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}
