/**
 * Generated by orval + scripts/restructure-api.ts.
 * Do not edit manually — re-run `pnpm api:generate`.
 */
import { orvalApiClient } from "@/api/orval-mutator";
import type { PostLogoutResponse } from "../types/PostLogoutResponse";

const getLogoutUrl = () => {
  return `/api/refresh-tokens/logout`;
};

export const postLogout = async (
  options?: Parameters<typeof orvalApiClient>[1],
): Promise<PostLogoutResponse> => {
  return orvalApiClient<PostLogoutResponse>(getLogoutUrl(), {
    ...options,
    method: "POST",
  });
};
