/**
 * Generated by orval + scripts/restructure-api.ts.
 * Do not edit manually — re-run `pnpm api:generate`.
 */
import { orvalApiClient } from "@/api/orval-mutator";
import type { PostReissueResponse } from "../types/PostReissueResponse";

const getReissueUrl = () => {
  return `/api/refresh-tokens/reissue`;
};

export const postReissue = async (
  options?: Parameters<typeof orvalApiClient>[1],
): Promise<PostReissueResponse> => {
  return orvalApiClient<PostReissueResponse>(getReissueUrl(), {
    ...options,
    method: "POST",
  });
};
