/**
 * Generated by orval + scripts/restructure-api.ts.
 * Do not edit manually — re-run `pnpm api:generate`.
 */
export type CreateDebateRequestAgreement =
  (typeof CreateDebateRequestAgreement)[keyof typeof CreateDebateRequestAgreement];

export const CreateDebateRequestAgreement = {
  AGREE: "AGREE",
  DISAGREE: "DISAGREE",
} as const;
