/**
 * Generated by orval + scripts/restructure-api.ts.
 * Do not edit manually — re-run `pnpm api:generate`.
 */
export type DebateDetailResponseOpponentAgreement =
  (typeof DebateDetailResponseOpponentAgreement)[keyof typeof DebateDetailResponseOpponentAgreement];

export const DebateDetailResponseOpponentAgreement = {
  AGREE: "AGREE",
  DISAGREE: "DISAGREE",
} as const;
