/**
 * Generated by orval + scripts/restructure-api.ts.
 * Do not edit manually — re-run `pnpm api:generate`.
 */
import type { DebateListResponseCategory } from "./DebateListResponseCategory";
import type { DebateListResponseStatus } from "./DebateListResponseStatus";

export interface DebateListResponse {
  /** 토론 ID */
  debateId?: number;
  /** 토론 제목 */
  title?: string;
  /** 카테고리 */
  category?: DebateListResponseCategory;
  /** 토론 상태 */
  status?: DebateListResponseStatus;
  /** 찬성 프로필 이미지 */
  agreeImageUrl?: string;
  /** 반대 프로필 이미지 */
  disagreeImageUrl?: string;
}
