/**
 * Generated by orval + scripts/restructure-api.ts.
 * Do not edit manually — re-run `pnpm api:generate`.
 */
export type DebateListResponseStatus =
  (typeof DebateListResponseStatus)[keyof typeof DebateListResponseStatus];

export const DebateListResponseStatus = {
  IN_PROGRESS: "IN_PROGRESS",
  WAITING: "WAITING",
  CLOSED: "CLOSED",
} as const;
