/**
 * Generated by orval + scripts/restructure-api.ts.
 * Do not edit manually — re-run `pnpm api:generate`.
 */
export type DebateDetailResponseStatus =
  (typeof DebateDetailResponseStatus)[keyof typeof DebateDetailResponseStatus];

export const DebateDetailResponseStatus = {
  IN_PROGRESS: "IN_PROGRESS",
  WAITING: "WAITING",
  CLOSED: "CLOSED",
} as const;
