/**
 * Generated by orval + scripts/restructure-api.ts.
 * Do not edit manually — re-run `pnpm api:generate`.
 */
export type DebateDetailResponseHostAgreement =
  (typeof DebateDetailResponseHostAgreement)[keyof typeof DebateDetailResponseHostAgreement];

export const DebateDetailResponseHostAgreement = {
  AGREE: "AGREE",
  DISAGREE: "DISAGREE",
} as const;
