/**
 * Generated by orval + scripts/restructure-api.ts.
 * Do not edit manually — re-run `pnpm api:generate`.
 */
import type { CommonResponse } from "@/api/common/types/CommonResponse";
import type { DebateListResponse } from "./DebateListResponse";

export type GetDebateListResponse = CommonResponse<{
  content?: DebateListResponse[];
  pageNumber?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
  isFirst?: boolean;
  isLast?: boolean;
}>;
