/**
 * Generated by orval + scripts/restructure-api.ts.
 * Do not edit manually — re-run `pnpm api:generate`.
 */

import type { Pageable } from "@/api/common/types/Pageable";
import type { GetDebateListCategory } from "./GetDebateListCategory";
import type { GetDebateListStatus } from "./GetDebateListStatus";

export type GetDebateListRequest = {
  /**
   * 카테고리 필터
   */
  category?: GetDebateListCategory;
  /**
   * 토론 상태 필터 (WAITING / IN_PROGRESS / CLOSED)
   */
  status: GetDebateListStatus;
  pageable: Pageable;
};
