/**
 * Generated by orval + scripts/restructure-api.ts.
 * Do not edit manually — re-run `pnpm api:generate`.
 */
export type GetDebateListStatus =
  (typeof GetDebateListStatus)[keyof typeof GetDebateListStatus];

export const GetDebateListStatus = {
  IN_PROGRESS: "IN_PROGRESS",
  WAITING: "WAITING",
  CLOSED: "CLOSED",
} as const;
