/**
 * Generated by orval + scripts/restructure-api.ts.
 * Do not edit manually — re-run `pnpm api:generate`.
 */
import type { CommonResponse } from "@/api/common/types/CommonResponse";
import type { DebateDetailResponseCategory } from "./DebateDetailResponseCategory";
import type { DebateDetailResponseHostAgreement } from "./DebateDetailResponseHostAgreement";
import type { DebateDetailResponseOpponentAgreement } from "./DebateDetailResponseOpponentAgreement";
import type { DebateDetailResponseStatus } from "./DebateDetailResponseStatus";

export type GetDebateResponse = CommonResponse<{
  /** 토론 ID */
  debateId?: number;
  /** 토론 제목 */
  title?: string;
  /** 토론 설명 */
  content?: string;
  /** 카테고리 */
  category?: DebateDetailResponseCategory;
  /** 찬성 입장 라벨 */
  agreeLabel?: string;
  /** 반대 입장 라벨 */
  disagreeLabel?: string;
  /** 토론 상태 */
  status?: DebateDetailResponseStatus;
  /** 호스트 닉네임 */
  hostNickname?: string;
  /** 호스트 찬반 입장 */
  hostAgreement?: DebateDetailResponseHostAgreement;
  /** 상대방 닉네임 (미참여 시 null) */
  opponentNickname?: string;
  /** 상대방 찬반 입장 (미참여 시 null) */
  opponentAgreement?: DebateDetailResponseOpponentAgreement;
}>;
