/**
 * Generated by orval + scripts/restructure-api.ts.
 * Do not edit manually — re-run `pnpm api:generate`.
 */
export type PostFinishDebateRequest = {
  debateId: number;
  /**
   * @minItems 6
   * @maxItems 6
   */
  s3ObjectKeyList: string[];
};
