/**
 * Generated by orval + scripts/restructure-api.ts.
 * Do not edit manually — re-run `pnpm api:generate`.
 */
import type { CreateDebateRequestAgreement } from "./CreateDebateRequestAgreement";
import type { CreateDebateRequestCategory } from "./CreateDebateRequestCategory";

export type PostCreateDebateRequest = {
  /**
   * 토론 제목
   * @minLength 1
   */
  title: string;
  /** 토론 설명 */
  content?: string;
  /** 카테고리 */
  category: CreateDebateRequestCategory;
  /**
   * 찬성 입장 라벨
   * @minLength 1
   */
  agreeLabel: string;
  /**
   * 반대 입장 라벨
   * @minLength 1
   */
  disagreeLabel: string;
  /** 호스트 찬반 입장 (AGREE / DISAGREE) */
  agreement: CreateDebateRequestAgreement;
};
