/**
 * Generated by orval + scripts/restructure-api.ts.
 * Do not edit manually — re-run `pnpm api:generate`.
 */
import type { CommonResponse } from "@/api/common/types/CommonResponse";

export type PostCreateDebateResponse = CommonResponse<{
  /** 토론 ID */
  debateId?: number;
  /** 초대 코드 (UUID) */
  inviteCode?: string;
}>;
