/**
 * Generated by orval + scripts/restructure-api.ts.
 * Do not edit manually — re-run `pnpm api:generate`.
 */
import type { DevLoginRequest } from "./DevLoginRequest";

export type PostLogin1Request = DevLoginRequest;
