/**
 * Generated by orval + scripts/restructure-api.ts.
 * Do not edit manually — re-run `pnpm api:generate`.
 */
import { orvalApiClient } from "@/api/orval-mutator";
import { orvalParamsSerializer } from "@/api/orval-params-serializer";
import type { GetMyDebateListRequest as MyDebateListParams } from "../types/GetMyDebateListRequest";
import type { GetMyDebateListResponse } from "../types/GetMyDebateListResponse";

const getMyDebateListUrl = (params: MyDebateListParams) => {
  const stringifiedParams = orvalParamsSerializer(params);

  return stringifiedParams.length > 0
    ? `/api/users/debates/my?${stringifiedParams}`
    : `/api/users/debates/my`;
};

export const getMyDebateList = async (
  params: MyDebateListParams,
  options?: Parameters<typeof orvalApiClient>[1],
): Promise<GetMyDebateListResponse> => {
  return orvalApiClient<GetMyDebateListResponse>(getMyDebateListUrl(params), {
    ...options,
    method: "GET",
  });
};
