/**
 * Generated by orval + scripts/restructure-api.ts.
 * Do not edit manually — re-run `pnpm api:generate`.
 */
import { orvalApiClient } from "@/api/orval-mutator";
import type { GetCheckResponse } from "../types/GetCheckResponse";

const getCheckUrl = () => {
  return `/api/notifications/check`;
};

export const getCheck = async (
  options?: Parameters<typeof orvalApiClient>[1],
): Promise<GetCheckResponse> => {
  return orvalApiClient<GetCheckResponse>(getCheckUrl(), {
    ...options,
    method: "GET",
  });
};
