/**
 * Generated by orval + scripts/restructure-api.ts.
 * Do not edit manually — re-run `pnpm api:generate`.
 */
import { orvalApiClient } from "@/api/orval-mutator";
import type { GetView1Request as View1Params } from "../types/GetView1Request";
import type { GetView1Response } from "../types/GetView1Response";

const getView1Url = (params: View1Params) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/notifications?${stringifiedParams}`
    : `/api/notifications`;
};

export const getView1 = async (
  params: View1Params,
  options?: Parameters<typeof orvalApiClient>[1],
): Promise<GetView1Response> => {
  return orvalApiClient<GetView1Response>(getView1Url(params), {
    ...options,
    method: "GET",
  });
};
