/**
 * Generated by orval + scripts/restructure-api.ts.
 * Do not edit manually — re-run `pnpm api:generate`.
 */
import { orvalApiClient } from "@/api/orval-mutator";
import type { GetViewRequest as ViewParams } from "../types/GetViewRequest";
import type { GetViewResponse } from "../types/GetViewResponse";

const getViewUrl = (params: ViewParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/notifications?${stringifiedParams}`
    : `/api/notifications`;
};

export const getView = async (
  params: ViewParams,
  options?: Parameters<typeof orvalApiClient>[1],
): Promise<GetViewResponse> => {
  return orvalApiClient<GetViewResponse>(getViewUrl(params), {
    ...options,
    method: "GET",
  });
};
