/**
 * Generated by orval + scripts/restructure-api.ts.
 * Do not edit manually — re-run `pnpm api:generate`.
 */
import { orvalApiClient } from "@/api/orval-mutator";
import type { PatchReadAllResponse } from "../types/PatchReadAllResponse";

const getReadAllUrl = () => {
  return `/api/notifications`;
};

export const patchReadAll = async (
  options?: Parameters<typeof orvalApiClient>[1],
): Promise<PatchReadAllResponse> => {
  return orvalApiClient<PatchReadAllResponse>(getReadAllUrl(), {
    ...options,
    method: "PATCH",
  });
};
