/**
 * Generated by orval + scripts/restructure-api.ts.
 * Do not edit manually — re-run `pnpm api:generate`.
 */
import { orvalApiClient } from "@/api/orval-mutator";
import type { PatchReadResponse } from "../types/PatchReadResponse";

const getReadUrl = (notificationId: number) => {
  return `/api/notifications/${notificationId}`;
};

export const patchRead = async (
  notificationId: number,
  options?: Parameters<typeof orvalApiClient>[1],
): Promise<PatchReadResponse> => {
  return orvalApiClient<PatchReadResponse>(getReadUrl(notificationId), {
    ...options,
    method: "PATCH",
  });
};
