/**
 * Generated by orval + scripts/restructure-api.ts.
 * Do not edit manually — re-run `pnpm api:generate`.
 */
import { orvalApiClient } from "@/api/orval-mutator";
import type { GetHomeResponse } from "../types/GetHomeResponse";

const getHomeUrl = () => {
  return `/api/users/home`;
};

export const getHome = async (
  options?: Parameters<typeof orvalApiClient>[1],
): Promise<GetHomeResponse> => {
  return orvalApiClient<GetHomeResponse>(getHomeUrl(), {
    ...options,
    method: "GET",
  });
};
