/**
 * Generated by orval + scripts/restructure-api.ts.
 * Do not edit manually — re-run `pnpm api:generate`.
 */
import { orvalApiClient } from "@/api/orval-mutator";
import type { GetMyPageResponse } from "../types/GetMyPageResponse";

const getMyPageUrl = () => {
  return `/api/users/my`;
};

export const getMyPage = async (
  options?: Parameters<typeof orvalApiClient>[1],
): Promise<GetMyPageResponse> => {
  return orvalApiClient<GetMyPageResponse>(getMyPageUrl(), {
    ...options,
    method: "GET",
  });
};
