/**
 * Generated by orval + scripts/restructure-api.ts.
 * Do not edit manually — re-run `pnpm api:generate`.
 */
import { orvalApiClient } from "@/api/orval-mutator";
import type { GetViewProfileImageResponse } from "../types/GetViewProfileImageResponse";

const getViewProfileImageUrl = () => {
  return `/api/users/my/profile-image`;
};

export const getViewProfileImage = async (
  options?: Parameters<typeof orvalApiClient>[1],
): Promise<GetViewProfileImageResponse> => {
  return orvalApiClient<GetViewProfileImageResponse>(getViewProfileImageUrl(), {
    ...options,
    method: "GET",
  });
};
