/**
 * Generated by orval + scripts/restructure-api.ts.
 * Do not edit manually — re-run `pnpm api:generate`.
 */
import { orvalApiClient } from "@/api/orval-mutator";
import type { PatchModifyProfileRequest as UpdateProfileRequest } from "../types/PatchModifyProfileRequest";
import type { PatchModifyProfileResponse } from "../types/PatchModifyProfileResponse";

const getModifyProfileUrl = () => {
  return `/api/users/my/profile`;
};

export const patchModifyProfile = async (
  updateProfileRequest: UpdateProfileRequest,
  options?: Parameters<typeof orvalApiClient>[1],
): Promise<PatchModifyProfileResponse> => {
  return orvalApiClient<PatchModifyProfileResponse>(getModifyProfileUrl(), {
    ...options,
    method: "PATCH",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(updateProfileRequest),
  });
};
