/**
 * Generated by orval + scripts/restructure-api.ts.
 * Do not edit manually — re-run `pnpm api:generate`.
 */
import { orvalApiClient } from "@/api/orval-mutator";
import type { GetMyPollListRequest as MyPollListParams } from "../types/GetMyPollListRequest";
import type { GetMyPollListResponse } from "../types/GetMyPollListResponse";

const getMyPollListUrl = (params: MyPollListParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/users/polls/my?${stringifiedParams}`
    : `/api/users/polls/my`;
};

export const getMyPollList = async (
  params: MyPollListParams,
  options?: Parameters<typeof orvalApiClient>[1],
): Promise<GetMyPollListResponse> => {
  return orvalApiClient<GetMyPollListResponse>(getMyPollListUrl(params), {
    ...options,
    method: "GET",
  });
};
