/**
 * Generated by orval + scripts/restructure-api.ts.
 * Do not edit manually — re-run `pnpm api:generate`.
 */
import { orvalApiClient } from "@/api/orval-mutator";
import type { PostVoteRequest as CreateUserPollRequest } from "../types/PostVoteRequest";
import type { PostVoteResponse } from "../types/PostVoteResponse";

const getVoteUrl = () => {
  return `/api/users/polls`;
};

export const postVote = async (
  createUserPollRequest: CreateUserPollRequest,
  options?: Parameters<typeof orvalApiClient>[1],
): Promise<PostVoteResponse> => {
  return orvalApiClient<PostVoteResponse>(getVoteUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createUserPollRequest),
  });
};
