/**
 * Generated by orval + scripts/restructure-api.ts.
 * Do not edit manually — re-run `pnpm api:generate`.
 */
export interface LoginAuthResponse {
  accessToken?: string;
  signupToken?: string;
  isNewUser?: boolean;
}
