/**
 * Generated by orval + scripts/restructure-api.ts.
 * Do not edit manually — re-run `pnpm api:generate`.
 */
export interface PresignedUrlResponse {
  presignedUrl?: string;
  s3objectKey?: string;
}
