/**
 * Generated by orval + scripts/restructure-api.ts.
 * Do not edit manually — re-run `pnpm api:generate`.
 */
import type { CommonResponse } from "@/api/common/types/CommonResponse";
import type { PopularDebate } from "./PopularDebate";
import type { PopularPoll } from "./PopularPoll";

export type GetHomeResponse = CommonResponse<{
  popularPolls?: PopularPoll[];
  openDebates?: PopularDebate[];
}>;
