/**
 * Generated by orval + scripts/restructure-api.ts.
 * Do not edit manually — re-run `pnpm api:generate`.
 */
import type { CommonResponse } from "@/api/common/types/CommonResponse";

export type GetMyPageResponse = CommonResponse<{
  nickname?: string;
  presignedUrl?: string;
  pollCount?: number;
  debateCount?: number;
}>;
