/**
 * Generated by orval + scripts/restructure-api.ts.
 * Do not edit manually — re-run `pnpm api:generate`.
 */
export type PatchModifyProfileRequest = {
  /** @minLength 1 */
  nickname: string;
  s3ObjectKey?: string;
};
