/**
 * Generated by orval + scripts/restructure-api.ts.
 * Do not edit manually — re-run `pnpm api:generate`.
 */
export type PopularPollCategory =
  (typeof PopularPollCategory)[keyof typeof PopularPollCategory];

export const PopularPollCategory = {
  ISSUE: "ISSUE",
  LOVE: "LOVE",
  SPORTS: "SPORTS",
  GAME: "GAME",
  CULTURE_TECH: "CULTURE_TECH",
  OTHERS: "OTHERS",
} as const;
