/**
 * Generated by orval + scripts/restructure-api.ts.
 * Do not edit manually — re-run `pnpm api:generate`.
 */
import type { PopularPollCategory } from "./PopularPollCategory";

export interface PopularPoll {
  title?: string;
  category?: PopularPollCategory;
  voteCount?: number;
  dDay?: string;
}
