/**
 * Generated by orval + scripts/restructure-api.ts.
 * Do not edit manually — re-run `pnpm api:generate`.
 */
import type { PopularDebateCategory } from "./PopularDebateCategory";

export interface PopularDebate {
  title?: string;
  category?: PopularDebateCategory;
}
