/**
 * Generated by orval + scripts/restructure-api.ts.
 * Do not edit manually — re-run `pnpm api:generate`.
 */
export type FindMyDebateResponseCategoryType =
  (typeof FindMyDebateResponseCategoryType)[keyof typeof FindMyDebateResponseCategoryType];

export const FindMyDebateResponseCategoryType = {
  ISSUE: "ISSUE",
  LOVE: "LOVE",
  SPORTS: "SPORTS",
  GAME: "GAME",
  CULTURE_TECH: "CULTURE_TECH",
  OTHERS: "OTHERS",
} as const;
