/**
 * Generated by orval + scripts/restructure-api.ts.
 * Do not edit manually — re-run `pnpm api:generate`.
 */
import type { FindMyDebateResponseCategoryType } from "./FindMyDebateResponseCategoryType";

export interface FindMyDebateResponse {
  debateId?: number;
  title?: string;
  categoryType?: FindMyDebateResponseCategoryType;
  agrees?: number;
  disagrees?: number;
}
