/**
 * Generated by orval + scripts/restructure-api.ts.
 * Do not edit manually — re-run `pnpm api:generate`.
 */
import type { CommonResponse } from "@/api/common/types/CommonResponse";
import type { PageResponse } from "@/api/common/types/PageResponse";
import type { FindMyDebateResponseCategoryType } from "./FindMyDebateResponseCategoryType";

export type GetMyDebateListResponse = CommonResponse<
  PageResponse<{
    title?: string;
    categoryType?: FindMyDebateResponseCategoryType;
    agrees?: number;
    disagrees?: number;
  }>
>;
