/**
 * Generated by orval + scripts/restructure-api.ts.
 * Do not edit manually — re-run `pnpm api:generate`.
 */
import type { CommonResponse } from "@/api/common/types/CommonResponse";
import type { FindMyDebateResponse } from "./FindMyDebateResponse";

export type GetMyDebateListResponse = CommonResponse<{
  content?: FindMyDebateResponse[];
  pageNumber?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
  isFirst?: boolean;
  isLast?: boolean;
}>;
