/**
 * Generated by orval + scripts/restructure-api.ts.
 * Do not edit manually — re-run `pnpm api:generate`.
 */

import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { useQuery } from "@tanstack/react-query";
import type { SecondParameter } from "@/api/common/query-helpers";
import { withQueryKey } from "@/api/common/query-helpers";
import type { ErrorType, orvalApiClient } from "@/api/orval-mutator";
import { getDebate } from "../api/getDebate";

export const getGetDebateQueryKey = (debateId: number) => {
  return [`/api/debates/${debateId}`] as const;
};

export const getGetDebateQueryOptions = <
  TData = Awaited<ReturnType<typeof getDebate>>,
  TError = ErrorType<unknown>,
>(
  debateId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getDebate>>, TError, TData>
    >;
    request?: SecondParameter<typeof orvalApiClient>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetDebateQueryKey(debateId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getDebate>>> = ({
    signal,
  }) => getDebate(debateId, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: debateId !== null && debateId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getDebate>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type GetDebateQueryResult = NonNullable<
  Awaited<ReturnType<typeof getDebate>>
>;
export type GetDebateQueryError = ErrorType<unknown>;

export function useGetDebate<
  TData = Awaited<ReturnType<typeof getDebate>>,
  TError = ErrorType<unknown>,
>(
  debateId: number,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getDebate>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDebate>>,
          TError,
          Awaited<ReturnType<typeof getDebate>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof orvalApiClient>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetDebate<
  TData = Awaited<ReturnType<typeof getDebate>>,
  TError = ErrorType<unknown>,
>(
  debateId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getDebate>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDebate>>,
          TError,
          Awaited<ReturnType<typeof getDebate>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof orvalApiClient>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetDebate<
  TData = Awaited<ReturnType<typeof getDebate>>,
  TError = ErrorType<unknown>,
>(
  debateId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getDebate>>, TError, TData>
    >;
    request?: SecondParameter<typeof orvalApiClient>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 토론 상세 조회
 */

export function useGetDebate<
  TData = Awaited<ReturnType<typeof getDebate>>,
  TError = ErrorType<unknown>,
>(
  debateId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getDebate>>, TError, TData>
    >;
    request?: SecondParameter<typeof orvalApiClient>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetDebateQueryOptions(debateId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}
