/**
 * Generated by orval + scripts/restructure-api.ts.
 * Do not edit manually — re-run `pnpm api:generate`.
 */

import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from "@tanstack/react-query";
import { useMutation } from "@tanstack/react-query";
import type { SecondParameter } from "@/api/common/query-helpers";
import type { BodyType, ErrorType, orvalApiClient } from "@/api/orval-mutator";
import { postCreateDebate as createDebate } from "../api/postCreateDebate";
import type { PostCreateDebateRequest as CreateDebateRequest } from "../types/PostCreateDebateRequest";

export const getCreateDebateMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createDebate>>,
    TError,
    { data: BodyType<CreateDebateRequest> },
    TContext
  >;
  request?: SecondParameter<typeof orvalApiClient>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createDebate>>,
  TError,
  { data: BodyType<CreateDebateRequest> },
  TContext
> => {
  const mutationKey = ["createDebate"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createDebate>>,
    { data: BodyType<CreateDebateRequest> }
  > = (props) => {
    const { data } = props ?? {};

    return createDebate(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateDebateMutationResult = NonNullable<
  Awaited<ReturnType<typeof createDebate>>
>;
export type CreateDebateMutationBody = BodyType<CreateDebateRequest>;
export type CreateDebateMutationError = ErrorType<unknown>;

/**
 * @summary 토론 생성
 */
export const usePostCreateDebate = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createDebate>>,
      TError,
      { data: BodyType<CreateDebateRequest> },
      TContext
    >;
    request?: SecondParameter<typeof orvalApiClient>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createDebate>>,
  TError,
  { data: BodyType<CreateDebateRequest> },
  TContext
> => {
  return useMutation(getCreateDebateMutationOptions(options), queryClient);
};
