/**
 * Generated by orval + scripts/restructure-api.ts.
 * Do not edit manually — re-run `pnpm api:generate`.
 */
import { orvalApiClient } from "@/api/orval-mutator";
import type { PostSignup1Request as DevLoginRequest } from "../types/PostSignup1Request";
import type { PostSignup1Response } from "../types/PostSignup1Response";

const getSignup1Url = () => {
  return `/auth/dev/signup`;
};

export const postSignup1 = async (
  devLoginRequest: DevLoginRequest,
  options?: Parameters<typeof orvalApiClient>[1],
): Promise<PostSignup1Response> => {
  return orvalApiClient<PostSignup1Response>(getSignup1Url(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(devLoginRequest),
  });
};
