/**
 * Generated by orval + scripts/restructure-api.ts.
 * Do not edit manually — re-run `pnpm api:generate`.
 */
import { orvalApiClient } from "@/api/orval-mutator";
import type { PostLogin1Request as DevLoginRequest } from "../types/PostLogin1Request";
import type { PostLogin1Response } from "../types/PostLogin1Response";

const getLogin1Url = () => {
  return `/auth/dev/login`;
};

export const postLogin1 = async (
  devLoginRequest: DevLoginRequest,
  options?: Parameters<typeof orvalApiClient>[1],
): Promise<PostLogin1Response> => {
  return orvalApiClient<PostLogin1Response>(getLogin1Url(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(devLoginRequest),
  });
};
