/**
 * Generated by orval + scripts/restructure-api.ts.
 * Do not edit manually — re-run `pnpm api:generate`.
 */
import type { CommonResponse } from "@/api/common/types/CommonResponse";
import type { PresignedUrlResponse } from "@/api/common/types/PresignedUrlResponse";

export type GetPreUpload1Response = CommonResponse<PresignedUrlResponse>;
