/**
 * Generated by orval + scripts/restructure-api.ts.
 * Do not edit manually — re-run `pnpm api:generate`.
 */
export type LoginAuthRequestProviderType =
  (typeof LoginAuthRequestProviderType)[keyof typeof LoginAuthRequestProviderType];

export const LoginAuthRequestProviderType = {
  GOOGLE: "GOOGLE",
  KAKAO: "KAKAO",
} as const;
