/**
 * Generated by orval + scripts/restructure-api.ts.
 * Do not edit manually — re-run `pnpm api:generate`.
 */
import type { CommonResponse } from "@/api/common/types/CommonResponse";
import type { SignupAuthResponse } from "@/api/common/types/SignupAuthResponse";

export type PostSignupResponse = CommonResponse<SignupAuthResponse>;
