/**
 * Generated by orval + scripts/restructure-api.ts.
 * Do not edit manually — re-run `pnpm api:generate`.
 */
import type { LoginAuthRequestProviderType } from "./LoginAuthRequestProviderType";

export type PostLoginRequest = {
  providerType: LoginAuthRequestProviderType;
  /** @minLength 1 */
  socialCode: string;
};
