/**
 * Generated by orval + scripts/restructure-api.ts.
 * Do not edit manually — re-run `pnpm api:generate`.
 */
export type PostSignupRequest = {
  /** @minLength 1 */
  signupToken: string;
  /**
   * @minLength 2
   * @maxLength 20
   */
  nickname: string;
  /** @minLength 1 */
  s3ObjectKey: string;
};
