/**
 * Generated by orval + scripts/restructure-api.ts.
 * Do not edit manually — re-run `pnpm api:generate`.
 */
import type { CommonResponse } from "@/api/common/types/CommonResponse";
import type { LoginAuthResponse } from "@/api/common/types/LoginAuthResponse";

export type PostLoginResponse = CommonResponse<LoginAuthResponse>;
