/**
 * Generated by orval + scripts/restructure-api.ts.
 * Do not edit manually — re-run `pnpm api:generate`.
 */
import { orvalApiClient } from "@/api/orval-mutator";
import type { GetViewDetailsResponse } from "../types/GetViewDetailsResponse";

const getViewDetailsUrl = (pollId: number) => {
  return `/api/polls/${pollId}`;
};

export const getViewDetails = async (
  pollId: number,
  options?: Parameters<typeof orvalApiClient>[1],
): Promise<GetViewDetailsResponse> => {
  return orvalApiClient<GetViewDetailsResponse>(getViewDetailsUrl(pollId), {
    ...options,
    method: "GET",
  });
};
