/**
 * Generated by orval + scripts/restructure-api.ts.
 * Do not edit manually — re-run `pnpm api:generate`.
 */
import { orvalApiClient } from "@/api/orval-mutator";
import { orvalParamsSerializer } from "@/api/orval-params-serializer";
import type { GetView1Request as View1Params } from "../types/GetView1Request";
import type { GetView1Response } from "../types/GetView1Response";

const getView1Url = (params: View1Params) => {
  const stringifiedParams = orvalParamsSerializer(params);

  return stringifiedParams.length > 0
    ? `/api/polls?${stringifiedParams}`
    : `/api/polls`;
};

export const getView1 = async (
  params: View1Params,
  options?: Parameters<typeof orvalApiClient>[1],
): Promise<GetView1Response> => {
  return orvalApiClient<GetView1Response>(getView1Url(params), {
    ...options,
    method: "GET",
  });
};
