/**
 * Generated by orval + scripts/restructure-api.ts.
 * Do not edit manually — re-run `pnpm api:generate`.
 */
export type CreateUserPollRequestAgreement =
  (typeof CreateUserPollRequestAgreement)[keyof typeof CreateUserPollRequestAgreement];

export const CreateUserPollRequestAgreement = {
  AGREE: "AGREE",
  DISAGREE: "DISAGREE",
} as const;
