/**
 * Generated by orval + scripts/restructure-api.ts.
 * Do not edit manually — re-run `pnpm api:generate`.
 */
import type { FindMyPollResponseCategoryType } from "./FindMyPollResponseCategoryType";

export interface FindMyPollResponse {
  pollId?: number;
  pollName?: string;
  categoryType?: FindMyPollResponseCategoryType;
  agreeNickname?: string;
  disagreeNickname?: string;
  voteCount?: number;
}
