/**
 * Generated by orval + scripts/restructure-api.ts.
 * Do not edit manually — re-run `pnpm api:generate`.
 */
import type { Pageable } from "@/api/common/types/Pageable";

export type GetMyPollListRequest = {
  pageable: Pageable;
};
