/**
 * Generated by orval + scripts/restructure-api.ts.
 * Do not edit manually — re-run `pnpm api:generate`.
 */
import type { CommonResponse } from "@/api/common/types/CommonResponse";
import type { PageResponse } from "@/api/common/types/PageResponse";
import type { FindMyPollResponseCategoryType } from "./FindMyPollResponseCategoryType";

export type GetMyPollListResponse = CommonResponse<
  PageResponse<{
    pollId?: number;
    pollName?: string;
    categoryType?: FindMyPollResponseCategoryType;
    agreeNickname?: string;
    disagreeNickname?: string;
    voteCount?: number;
  }>
>;
