/**
 * Generated by orval + scripts/restructure-api.ts.
 * Do not edit manually — re-run `pnpm api:generate`.
 */
import type { CommonResponse } from "@/api/common/types/CommonResponse";
import type { FindMyPollResponse } from "./FindMyPollResponse";

export type GetMyPollListResponse = CommonResponse<{
  content?: FindMyPollResponse[];
  pageNumber?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
  isFirst?: boolean;
  isLast?: boolean;
}>;
