/**
 * Generated by orval + scripts/restructure-api.ts.
 * Do not edit manually — re-run `pnpm api:generate`.
 */
import type { CreateUserPollRequestAgreement } from "./CreateUserPollRequestAgreement";

export type PostVoteRequest = {
  pollId: number;
  agreement: CreateUserPollRequestAgreement;
};
