#!/usr/bin/env tsx
/**
 * Post-processes Orval's `tags-operations-split` output (in `.orval-staging/`)
 * into the domain-scoped `api/ types/` layout described in the project's
 * Orval guide. `hooks/` is hand-written on top of this output, not generated.
 * Runs automatically as part of `pnpm api:generate` — nothing here should
 * ever need hand-editing when the OpenAPI spec changes.
 *
 * Design notes (why this reads the way it does):
 * - Names are derived purely from what Orval already generated (the core
 *   call function's identifier already equals `camel(operationId)`), so this
 *   script never needs to fetch the spec itself.
 * - `{verb}{OperationId}` naming would double up when operationId already
 *   starts with the verb (e.g. GET `getDebateList` -> `getGetDebateList`).
 *   `stripLeadingVerb` removes that redundant prefix before re-adding it.
 * - `CommonResponse{X}` / `PageResponse{X}` wrapper interfaces are detected
 *   structurally (exact property sets) and collapsed into the shared
 *   generics in `src/api/common/types`, rather than kept as flattened
 *   per-operation interfaces.
 * - Any non-wrapper schema type used by 2+ domains (e.g. `Pageable`,
 *   `PresignedUrlResponse`) is promoted to `src/api/common/types` instead of
 *   being duplicated per domain.
 */
import fs from "node:fs";
import path from "node:path";
import {
  type InterfaceDeclaration,
  Node,
  Project,
  SyntaxKind,
  type TypeAliasDeclaration,
} from "ts-morph";

const ROOT = process.cwd();
const STAGING = path.join(ROOT, ".orval-staging");
const OUT = path.join(ROOT, "src/api");
const COMMON_TYPES_DIR = path.join(OUT, "common/types");

const HEADER =
  "/**\n * Generated by orval + scripts/restructure-api.ts.\n * Do not edit manually — re-run `pnpm api:generate`.\n */\n";

function pascal(input: string): string {
  return input
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join("");
}

function camel(input: string): string {
  const p = pascal(input);
  return p.length === 0 ? p : p.charAt(0).toLowerCase() + p.slice(1);
}

/** Strips a leading HTTP-verb word from an already-camelCase name, e.g.
 * `stripLeadingVerb("getDebateList", "GET") === "debateList"`, so re-adding
 * the verb during naming doesn't produce `getGetDebateList`. */
function stripLeadingVerb(baseName: string, verb: string): string {
  const verbLower = verb.toLowerCase();
  if (!baseName.toLowerCase().startsWith(verbLower)) return baseName;
  const rest = baseName.slice(verb.length);
  if (rest.length === 0) return baseName;
  if (!/^[A-Z0-9]/.test(rest)) return baseName;
  return rest.charAt(0).toLowerCase() + rest.slice(1);
}

type SchemaDecl = InterfaceDeclaration | TypeAliasDeclaration;

const WRAPPER_COMMON_RESPONSE_PROPS = ["data", "message", "success"]
  .sort()
  .join(",");
const WRAPPER_PAGE_RESPONSE_PROPS = [
  "content",
  "first",
  "last",
  "page",
  "size",
  "totalElements",
  "totalPages",
]
  .sort()
  .join(",");

function propsOf(decl: SchemaDecl): string[] | null {
  if (Node.isInterfaceDeclaration(decl)) {
    return decl.getProperties().map((p) => p.getName());
  }
  const typeNode = decl.getTypeNode();
  if (!typeNode || !Node.isTypeLiteral(typeNode)) return null;
  return typeNode.getProperties().map((p) => p.getName());
}

function isCommonResponseWrapper(decl: SchemaDecl): boolean {
  const props = propsOf(decl);
  return (
    props !== null &&
    [...props].sort().join(",") === WRAPPER_COMMON_RESPONSE_PROPS
  );
}

function isPageResponseWrapper(decl: SchemaDecl): boolean {
  const props = propsOf(decl);
  return (
    props !== null &&
    [...props].sort().join(",") === WRAPPER_PAGE_RESPONSE_PROPS
  );
}

function getPropertyTypeText(
  decl: SchemaDecl,
  propName: string,
): string | null {
  if (Node.isInterfaceDeclaration(decl)) {
    return decl.getProperty(propName)?.getTypeNode()?.getText() ?? null;
  }
  const typeNode = decl.getTypeNode();
  if (!typeNode || !Node.isTypeLiteral(typeNode)) return null;
  return typeNode.getProperty(propName)?.getTypeNode()?.getText() ?? null;
}

interface SchemaIndex {
  byName: Map<string, SchemaDecl>;
  /** Orval's enum-like schemas emit a `type X = typeof X[keyof typeof X]`
   * alias paired with a same-named `export const X = {...} as const;` value
   * declaration — both halves must move together or the type-only half
   * becomes an undefined value reference (TS2693). Keyed by name. */
  pairedConstText: Map<string, string>;
}

/**
 * Orval's `tags-operations-split` per-operation `.schemas.ts` files are
 * NOT reliably transitive — a response wrapper like `CommonResponseX` gets
 * embedded, but a type only reachable through one of its properties (e.g.
 * `X` itself, or `Pageable` inside a params object) is silently left
 * unresolved (no declaration, no import). The `schemas:` output directory
 * (`.orval-staging/model/`) is always complete and already carries correct
 * relative imports between its own files, so it's used as the single
 * source of truth for schema declarations instead.
 *
 * The one thing `model/` does NOT contain is a schema that only exists
 * inline in the spec (e.g. an anonymous request body never `$ref`'d to a
 * `components.schemas` entry) — Orval still names and emits it, but only
 * into that one operation's own `.schemas.ts` file. Those get merged in
 * as a lower-priority fallback via `mergeSchemaIndex` below, once per
 * domain's `.schemas.ts` files are read.
 */
function indexSchemaFiles(project: Project, filePaths: string[]): SchemaIndex {
  const byName = new Map<string, SchemaDecl>();
  const pairedConstText = new Map<string, string>();
  for (const filePath of filePaths) {
    const source = project.addSourceFileAtPath(filePath);
    for (const i of source.getInterfaces()) byName.set(i.getName(), i);
    for (const t of source.getTypeAliases()) byName.set(t.getName(), t);
    for (const v of source.getVariableStatements()) {
      if (!v.isExported()) continue;
      const decl = v.getDeclarations()[0];
      if (
        decl &&
        byName.has(decl.getName()) &&
        decl.getInitializer()?.getText().endsWith("as const")
      ) {
        pairedConstText.set(decl.getName(), v.getText());
      }
    }
  }
  return { byName, pairedConstText };
}

function indexModelDir(project: Project, modelDir: string): SchemaIndex {
  const filePaths = fs
    .readdirSync(modelDir)
    .filter((f) => f.endsWith(".ts") && f !== "index.ts")
    .map((f) => path.join(modelDir, f));
  return indexSchemaFiles(project, filePaths);
}

/** Adds `source`'s entries into `target` without overwriting a name `target`
 * already has — `model/` (the caller's existing entries) is the canonical
 * source whenever a name happens to exist in both. */
function mergeSchemaIndex(target: SchemaIndex, source: SchemaIndex): void {
  for (const [name, decl] of source.byName) {
    if (!target.byName.has(name)) target.byName.set(name, decl);
  }
  for (const [name, text] of source.pairedConstText) {
    if (!target.pairedConstText.has(name))
      target.pairedConstText.set(name, text);
  }
}

/** Resolves a `CommonResponse{X}` (optionally wrapping `PageResponse{Y}`)
 * interface into the generic alias text it should collapse to, e.g.
 * `CommonResponse<PageResponse<DebateListResponse>>`, plus the "leaf" type
 * name(s) (X, or Y) that still need to be relocated as real files. Returns
 * the original name unchanged (as both alias and leaf) if it doesn't match
 * the wrapper convention at all. */
function resolveResponse(
  index: SchemaIndex,
  responseTypeName: string,
): { alias: string; leafNames: string[] } {
  const decl = index.byName.get(responseTypeName);
  if (!decl || !isCommonResponseWrapper(decl)) {
    return { alias: responseTypeName, leafNames: [responseTypeName] };
  }
  const dataType = getPropertyTypeText(decl, "data");
  if (!dataType) return { alias: "CommonResponse<unknown>", leafNames: [] };
  const inner = index.byName.get(dataType);
  if (inner && isPageResponseWrapper(inner)) {
    const contentType = getPropertyTypeText(inner, "content") ?? "unknown[]";
    const itemType = contentType.replace(/\[\]$/, "");
    const leafNames = index.byName.has(itemType) ? [itemType] : [];
    return { alias: `CommonResponse<PageResponse<${itemType}>>`, leafNames };
  }
  const leafNames = index.byName.has(dataType) ? [dataType] : [];
  return { alias: `CommonResponse<${dataType}>`, leafNames };
}

interface RelocatedType {
  name: string;
  text: string;
}

/** BFS over the global schema index starting from `rootNames`, following
 * every identifier reference found in each declaration's own text (mirrors
 * what Orval's own `resolveTransitiveSchemas` should, but doesn't always,
 * do for `tags-operations-split`). Wrapper interfaces are skipped — they're
 * represented by the generic alias, never relocated as flat files. */
function collectTransitive(
  index: SchemaIndex,
  rootNames: string[],
): RelocatedType[] {
  const visited = new Map<string, RelocatedType>();
  const queue = [...rootNames];
  while (queue.length > 0) {
    const name = queue.shift();
    if (!name || visited.has(name)) continue;
    const decl = index.byName.get(name);
    if (!decl) continue;
    if (isCommonResponseWrapper(decl) || isPageResponseWrapper(decl)) continue;
    const pairedConst = index.pairedConstText.get(name);
    const text = pairedConst
      ? `${decl.getText()}\n\n${pairedConst}`
      : decl.getText();
    visited.set(name, { name, text });
    for (const otherName of index.byName.keys()) {
      if (otherName === name || visited.has(otherName)) continue;
      if (new RegExp(`\\b${otherName}\\b`).test(text)) queue.push(otherName);
    }
  }
  return [...visited.values()];
}

/** Strips a schema declaration down to just its property-list body text
 * (e.g. `{ debateId: number; title: string }`), for inlining a single-use
 * type directly at its one call site instead of keeping a separate file. */
function extractBodyText(decl: SchemaDecl): string {
  if (Node.isInterfaceDeclaration(decl)) {
    const text = decl.getText();
    return text.slice(text.indexOf("{"));
  }
  const typeNode = decl.getTypeNode();
  return typeNode ? typeNode.getText() : decl.getText();
}

interface OpMeta {
  domain: string;
  method: string;
  originalBaseName: string;
  apiName: string;
  requestSourceName: string | null;
  responseLeafNames: string[];
  responseTypeName: string;
  responseAlias: string;
  coreFnText: string;
  urlFnText: string;
}

const project = new Project({ skipAddingFilesFromTsConfig: true });

const domains = fs
  .readdirSync(STAGING, { withFileTypes: true })
  .filter((d) => d.isDirectory() && d.name !== "model")
  .map((d) => d.name)
  .sort();

const globalIndex = indexModelDir(project, path.join(STAGING, "model"));

for (const domain of domains) {
  const domainDir = path.join(STAGING, domain);
  const localSchemaFiles = fs
    .readdirSync(domainDir)
    .filter((f) => f.endsWith(".schemas.ts"))
    .map((f) => path.join(domainDir, f));
  if (localSchemaFiles.length === 0) continue;
  mergeSchemaIndex(globalIndex, indexSchemaFiles(project, localSchemaFiles));
}

const opMetas: OpMeta[] = [];
// typeName -> declaration text (assumed identical across domains for a given name)
const typeText = new Map<string, string>();
// typeName -> set of domains that reference it
const typeDomains = new Map<string, Set<string>>();
// typeName -> set of operations ("domain:apiName") that use it directly as
// their request or response type (not merely a nested/transitive reference).
// A name used by exactly one operation here is a candidate to inline
// directly into that operation's Request/Response file instead of keeping a
// same-content separate file — re-decided fresh on every regen, so it
// re-splits into a proper shared file automatically the moment a second
// operation starts using it too.
const rootUsage = new Map<string, Set<string>>();

for (const domain of domains) {
  const domainDir = path.join(STAGING, domain);
  const opFiles = fs
    .readdirSync(domainDir)
    .filter(
      (f) =>
        f.endsWith(".ts") &&
        !f.endsWith(".schemas.ts") &&
        !f.endsWith(".helpers.ts") &&
        f !== "index.ts",
    )
    .sort();

  for (const file of opFiles) {
    const opSource = project.addSourceFileAtPath(path.join(domainDir, file));

    const varStatements = opSource
      .getVariableStatements()
      .filter((v) => v.isExported());
    const coreStmt = varStatements.find((v) => {
      const initText =
        v.getDeclarations()[0]?.getInitializer()?.getText() ?? "";
      return (
        initText.includes("orvalApiClient(") ||
        initText.includes("orvalApiClient<")
      );
    });
    if (!coreStmt) throw new Error(`core call function not found in ${file}`);
    const coreDecl = coreStmt.getDeclarations()[0];
    const originalBaseName = coreDecl.getName();

    const urlStmt = varStatements.find((v) =>
      /^get.+Url$/.test(v.getDeclarations()[0].getName()),
    );
    if (!urlStmt) throw new Error(`url helper not found in ${file}`);

    const methodMatch = coreStmt.getText().match(/method:\s*'(\w+)'/);
    if (!methodMatch) throw new Error(`HTTP method not found in ${file}`);
    const method = methodMatch[1];

    const arrowFn = coreDecl.getInitializerIfKindOrThrow(
      SyntaxKind.ArrowFunction,
    );
    const returnTypeText = arrowFn.getReturnTypeNode()?.getText() ?? "";
    const responseMatch = returnTypeText.match(/^Promise<(.+)>$/);
    if (!responseMatch)
      throw new Error(`response type not found in ${file}: ${returnTypeText}`);
    const originalResponseName = responseMatch[1];

    // Orval always emits params in `(...pathParams, params?, body?, options?)`
    // order, so the request body — when present — is the last non-`options`
    // param. `.find()` here would grab a leading path param instead (e.g.
    // `debateId: number`) on any operation with both a path param and a
    // body, like `finishDebate(debateId, finishDebateRequest, options?)`.
    const params = arrowFn.getParameters();
    const requestParam = params.findLast((p) => p.getName() !== "options");
    const requestSourceName = requestParam?.getTypeNode()?.getText() ?? null;

    const strippedBase = stripLeadingVerb(originalBaseName, method);
    const methodPascal = pascal(method.toLowerCase());
    const apiName = camel(methodPascal) + pascal(strippedBase);
    const responseTypeName = `${methodPascal}${pascal(strippedBase)}Response`;

    const { alias: responseAlias, leafNames: responseLeafNames } =
      resolveResponse(globalIndex, originalResponseName);
    const requestRoots =
      requestSourceName && globalIndex.byName.has(requestSourceName)
        ? [requestSourceName]
        : [];

    for (const t of collectTransitive(globalIndex, [
      ...requestRoots,
      ...responseLeafNames,
    ])) {
      if (!typeText.has(t.name)) typeText.set(t.name, t.text);
      if (!typeDomains.has(t.name)) typeDomains.set(t.name, new Set());
      typeDomains.get(t.name)?.add(domain);
    }

    const operationKey = `${domain}:${apiName}`;
    for (const rootName of [...requestRoots, ...responseLeafNames]) {
      if (!rootUsage.has(rootName)) rootUsage.set(rootName, new Set());
      rootUsage.get(rootName)?.add(operationKey);
    }

    const coreFnText = coreStmt.getFullText().trim();
    const urlFnText = urlStmt
      .getFullText()
      .trim()
      .replace(/^export\s+/, "");

    opMetas.push({
      domain,
      method,
      originalBaseName,
      apiName,
      requestSourceName,
      responseLeafNames,
      responseTypeName,
      responseAlias,
      coreFnText,
      urlFnText,
    });
  }
}

const promotedTypes = new Set(
  [...typeDomains.entries()]
    .filter(([, doms]) => doms.size > 1)
    .map(([name]) => name),
);

// A type used as the direct request/response type of exactly one operation
// gets inlined into that operation's Request/Response file instead of kept
// as a same-content separate file. Removing it from typeText/typeDomains
// means it's neither written as its own file nor picked up as an available
// import below — every remaining reference to it gets replaced with its
// inlined body text at the two call sites that build Request.ts/Response.ts.
const inlineTypes = new Set(
  [...rootUsage.entries()]
    .filter(([, ops]) => ops.size === 1)
    .map(([name]) => name),
);
for (const name of inlineTypes) {
  typeText.delete(name);
  typeDomains.delete(name);
}

function typeImportPath(name: string, fromTypesDir: boolean): string {
  if (promotedTypes.has(name)) return `@/api/common/types/${name}`;
  return fromTypesDir ? `./${name}` : `../types/${name}`;
}

/** Rewrites bare identifier references inside a relocated type's text into
 * import statements, for every OTHER relocated type name it mentions. */
function resolveTypeImports(text: string, selfName: string): string {
  const referenced = new Set<string>();
  for (const otherName of typeText.keys()) {
    if (otherName === selfName) continue;
    if (new RegExp(`\\b${otherName}\\b`).test(text)) referenced.add(otherName);
  }
  if (referenced.size === 0) return text;
  const imports = [...referenced]
    .sort()
    .map((n) => `import type { ${n} } from "${typeImportPath(n, true)}";`)
    .join("\n");
  return `${imports}\n\n${text}`;
}

// ---- write common/types (promoted, shared across 2+ domains) ----
fs.mkdirSync(COMMON_TYPES_DIR, { recursive: true });
for (const name of promotedTypes) {
  const text = typeText.get(name);
  if (!text) continue;
  fs.writeFileSync(
    path.join(COMMON_TYPES_DIR, `${name}.ts`),
    `${HEADER + resolveTypeImports(text, name)}\n`,
  );
}

// ---- write per-domain types (used by exactly one domain) ----
for (const domain of domains) {
  const domainTypesDir = path.join(OUT, domain, "types");
  const namesForDomain = [...typeDomains.entries()]
    .filter(([name, doms]) => doms.has(domain) && !promotedTypes.has(name))
    .map(([name]) => name);
  if (namesForDomain.length === 0) continue;
  fs.mkdirSync(domainTypesDir, { recursive: true });
  for (const name of namesForDomain) {
    const text = typeText.get(name);
    if (!text) continue;
    fs.writeFileSync(
      path.join(domainTypesDir, `${name}.ts`),
      `${HEADER + resolveTypeImports(text, name)}\n`,
    );
  }
}

// ---- write Request/Response alias types and api/ per operation ----
for (const op of opMetas) {
  const apiDir = path.join(OUT, op.domain, "api");
  const typesDir = path.join(OUT, op.domain, "types");
  fs.mkdirSync(apiDir, { recursive: true });
  fs.mkdirSync(typesDir, { recursive: true });

  // A request "type" only exists if the leading param's type is an actual
  // schema declaration (not a scalar path param like `number`).
  const hasRequestType =
    op.requestSourceName !== null &&
    globalIndex.byName.has(op.requestSourceName);
  const strippedBase = stripLeadingVerb(op.originalBaseName, op.method);
  const requestTypeName = hasRequestType
    ? `${pascal(op.method.toLowerCase())}${pascal(strippedBase)}Request`
    : null;

  // Response.ts — thin alias over the (possibly generic) resolved type. If
  // the leaf payload type is only used by this one operation, its body is
  // inlined directly instead of kept as a same-content separate file.
  const responseLeaf = op.responseLeafNames[0];
  const finalResponseAlias =
    responseLeaf && inlineTypes.has(responseLeaf)
      ? op.responseAlias.replace(
          new RegExp(`\\b${responseLeaf}\\b`),
          extractBodyText(globalIndex.byName.get(responseLeaf) as SchemaDecl),
        )
      : op.responseAlias;
  const responseImports = [
    /\bCommonResponse</.test(finalResponseAlias)
      ? 'import type { CommonResponse } from "@/api/common/types/CommonResponse";'
      : null,
    /\bPageResponse</.test(finalResponseAlias)
      ? 'import type { PageResponse } from "@/api/common/types/PageResponse";'
      : null,
    ...[...typeText.keys()]
      .filter((n) => new RegExp(`\\b${n}\\b`).test(finalResponseAlias))
      .map((n) => `import type { ${n} } from "${typeImportPath(n, true)}";`),
  ].filter((x): x is string => x !== null);
  fs.writeFileSync(
    path.join(typesDir, `${op.responseTypeName}.ts`),
    `${HEADER}${responseImports.join("\n")}${responseImports.length ? "\n\n" : ""}export type ${op.responseTypeName} = ${finalResponseAlias};\n`,
  );

  // Request.ts — either a thin alias over the relocated request type, or
  // (if this is the only operation using it) its body inlined directly.
  if (requestTypeName && op.requestSourceName) {
    if (inlineTypes.has(op.requestSourceName)) {
      const bodyText = extractBodyText(
        globalIndex.byName.get(op.requestSourceName) as SchemaDecl,
      );
      const requestImports = [...typeText.keys()]
        .filter((n) => new RegExp(`\\b${n}\\b`).test(bodyText))
        .map((n) => `import type { ${n} } from "${typeImportPath(n, true)}";`);
      fs.writeFileSync(
        path.join(typesDir, `${requestTypeName}.ts`),
        `${HEADER}${requestImports.join("\n")}${requestImports.length ? "\n\n" : ""}export type ${requestTypeName} = ${bodyText};\n`,
      );
    } else {
      fs.writeFileSync(
        path.join(typesDir, `${requestTypeName}.ts`),
        `${HEADER}import type { ${op.requestSourceName} } from "${typeImportPath(op.requestSourceName, true)}";\n\nexport type ${requestTypeName} = ${op.requestSourceName};\n`,
      );
    }
  }

  // api/{apiName}.ts
  let coreFnText = op.coreFnText.replace(
    new RegExp(`\\b${op.originalBaseName}\\b`),
    op.apiName,
  );
  const originalResponseNameMatch = op.coreFnText.match(
    /Promise<([A-Za-z0-9_]+)>/,
  );
  if (originalResponseNameMatch) {
    const originalResponseName = originalResponseNameMatch[1];
    coreFnText = coreFnText.replace(
      new RegExp(`\\b${originalResponseName}\\b`, "g"),
      op.responseTypeName,
    );
  }

  // Request.ts is always the file that exists (whether it's an alias to a
  // separate type or an inlined body) — import from there, aliased back to
  // the original bare name the untouched core-function text expects.
  const requestImportSpecifier =
    requestTypeName === op.requestSourceName
      ? requestTypeName
      : `${requestTypeName} as ${op.requestSourceName}`;

  const apiImports = [
    'import { orvalApiClient } from "@/api/orval-mutator";',
    `import type { ${op.responseTypeName} } from "../types/${op.responseTypeName}";`,
    hasRequestType
      ? `import type { ${requestImportSpecifier} } from "../types/${requestTypeName}";`
      : null,
  ].filter((x): x is string => x !== null);

  fs.writeFileSync(
    path.join(apiDir, `${op.apiName}.ts`),
    `${HEADER}${apiImports.join("\n")}\n\n${op.urlFnText}\n\n${coreFnText}\n`,
  );
}

// ---- cleanup ----
fs.rmSync(STAGING, { recursive: true, force: true });

console.log(
  `Restructured ${opMetas.length} operations across ${domains.length} domains.`,
);
