/**
 * Generated by orval + scripts/restructure-api.ts.
 * Do not edit manually — re-run `pnpm api:generate`.
 */
import { orvalApiClient } from "@/api/orval-mutator";
import type { GetDebateListRequest as GetDebateListParams } from "../types/GetDebateListRequest";
import type { GetDebateListResponse } from "../types/GetDebateListResponse";

const getGetDebateListUrl = (params: GetDebateListParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/debates?${stringifiedParams}`
    : `/api/debates`;
};

/**
 * 상태(status) 필터는 필수, 카테고리 필터는 선택
 * @summary 토론 목록 조회
 */
export const getDebateList = async (
  params: GetDebateListParams,
  options?: Parameters<typeof orvalApiClient>[1],
): Promise<GetDebateListResponse> => {
  return orvalApiClient<GetDebateListResponse>(getGetDebateListUrl(params), {
    ...options,
    method: "GET",
  });
};
