/**
 * Generated by orval + scripts/restructure-api.ts.
 * Do not edit manually — re-run `pnpm api:generate`.
 */
import { orvalApiClient } from "@/api/orval-mutator";
import type { GetDebateResponse } from "../types/GetDebateResponse";

const getGetDebateUrl = (debateId: number) => {
  return `/api/debates/${debateId}`;
};

/**
 * 참여 모달에 필요한 라벨, 호스트/상대방 정보 반환
 * @summary 토론 상세 조회
 */
export const getDebate = async (
  debateId: number,
  options?: Parameters<typeof orvalApiClient>[1],
): Promise<GetDebateResponse> => {
  return orvalApiClient<GetDebateResponse>(getGetDebateUrl(debateId), {
    ...options,
    method: "GET",
  });
};
