/**
 * Generated by orval + scripts/restructure-api.ts.
 * Do not edit manually — re-run `pnpm api:generate`.
 */
import { orvalApiClient } from "@/api/orval-mutator";
import type { PostFinishDebateRequest as FinishDebateRequest } from "../types/PostFinishDebateRequest";
import type { PostFinishDebateResponse } from "../types/PostFinishDebateResponse";

const getFinishDebateUrl = (debateId: number) => {
  return `/api/debates/${debateId}`;
};

/**
 * 토론 종료 후 S3 음성파일 Argument와 매핑 및 Poll 생성
 * @summary 토론 종료
 */
export const postFinishDebate = async (
  debateId: number,
  finishDebateRequest: FinishDebateRequest,
  options?: Parameters<typeof orvalApiClient>[1],
): Promise<PostFinishDebateResponse> => {
  return orvalApiClient<PostFinishDebateResponse>(
    getFinishDebateUrl(debateId),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(finishDebateRequest),
    },
  );
};
