/**
 * Generated by orval + scripts/restructure-api.ts.
 * Do not edit manually — re-run `pnpm api:generate`.
 */
import { orvalApiClient } from "@/api/orval-mutator";
import type { PostCreateDebateRequest as CreateDebateRequest } from "../types/PostCreateDebateRequest";
import type { PostCreateDebateResponse } from "../types/PostCreateDebateResponse";

const getCreateDebateUrl = () => {
  return `/api/debates`;
};

/**
 * 토론 생성 후 inviteCode 반환
 * @summary 토론 생성
 */
export const postCreateDebate = async (
  createDebateRequest: CreateDebateRequest,
  options?: Parameters<typeof orvalApiClient>[1],
): Promise<PostCreateDebateResponse> => {
  return orvalApiClient<PostCreateDebateResponse>(getCreateDebateUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createDebateRequest),
  });
};
