/**
 * Generated by orval + scripts/restructure-api.ts.
 * Do not edit manually — re-run `pnpm api:generate`.
 */
import { orvalApiClient } from "@/api/orval-mutator";
import type { GetPreUploadRequest as PreUploadParams } from "../types/GetPreUploadRequest";
import type { GetPreUploadResponse } from "../types/GetPreUploadResponse";

const getPreUploadUrl = (params: PreUploadParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/auth/signup/profile-image?${stringifiedParams}`
    : `/auth/signup/profile-image`;
};

export const getPreUpload = async (
  params: PreUploadParams,
  options?: Parameters<typeof orvalApiClient>[1],
): Promise<GetPreUploadResponse> => {
  return orvalApiClient<GetPreUploadResponse>(getPreUploadUrl(params), {
    ...options,
    method: "GET",
  });
};
