/**
 * Generated by orval + scripts/restructure-api.ts.
 * Do not edit manually — re-run `pnpm api:generate`.
 */
import { orvalApiClient } from "@/api/orval-mutator";
import type { GetPreUpload1Request as PreUpload1Params } from "../types/GetPreUpload1Request";
import type { GetPreUpload1Response } from "../types/GetPreUpload1Response";

const getPreUpload1Url = (params: PreUpload1Params) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/auth/signup/profile-image?${stringifiedParams}`
    : `/auth/signup/profile-image`;
};

export const getPreUpload1 = async (
  params: PreUpload1Params,
  options?: Parameters<typeof orvalApiClient>[1],
): Promise<GetPreUpload1Response> => {
  return orvalApiClient<GetPreUpload1Response>(getPreUpload1Url(params), {
    ...options,
    method: "GET",
  });
};
