/**
 * Generated by orval + scripts/restructure-api.ts.
 * Do not edit manually — re-run `pnpm api:generate`.
 */
import { orvalApiClient } from "@/api/orval-mutator";
import type { PostLoginRequest as LoginAuthRequest } from "../types/PostLoginRequest";
import type { PostLoginResponse } from "../types/PostLoginResponse";

const getLoginUrl = () => {
  return `/auth/login`;
};

export const postLogin = async (
  loginAuthRequest: LoginAuthRequest,
  options?: Parameters<typeof orvalApiClient>[1],
): Promise<PostLoginResponse> => {
  return orvalApiClient<PostLoginResponse>(getLoginUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(loginAuthRequest),
  });
};
