/**
 * Generated by orval + scripts/restructure-api.ts.
 * Do not edit manually — re-run `pnpm api:generate`.
 */
import { orvalApiClient } from "@/api/orval-mutator";
import type { PostSignupRequest as SignupAuthRequest } from "../types/PostSignupRequest";
import type { PostSignupResponse } from "../types/PostSignupResponse";

const getSignupUrl = () => {
  return `/auth/signup`;
};

export const postSignup = async (
  signupAuthRequest: SignupAuthRequest,
  options?: Parameters<typeof orvalApiClient>[1],
): Promise<PostSignupResponse> => {
  return orvalApiClient<PostSignupResponse>(getSignupUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(signupAuthRequest),
  });
};
