/**
 * Generated by orval + scripts/restructure-api.ts.
 * Do not edit manually — re-run `pnpm api:generate`.
 */
export interface FindNotificationResponse {
  notificationId?: number;
  isRead?: boolean;
  targetId?: number;
  message?: string;
  noticeDateTime?: number;
}
