/**
 * Generated by orval + scripts/restructure-api.ts.
 * Do not edit manually — re-run `pnpm api:generate`.
 */
import type { CommonResponse } from "@/api/common/types/CommonResponse";
import type { FindNotificationResponse } from "./FindNotificationResponse";

export type GetView1Response = CommonResponse<{
  content?: FindNotificationResponse[];
  pageNumber?: number;
  size?: number;
  hasNext?: boolean;
  hasPrevious?: boolean;
  isFirst?: boolean;
  isLast?: boolean;
}>;
