/**
 * Generated by orval + scripts/restructure-api.ts.
 * Do not edit manually — re-run `pnpm api:generate`.
 */
import { orvalApiClient } from "@/api/orval-mutator";
import type { PostPreUploadBatchRequest as BatchPreUploadRequest } from "../types/PostPreUploadBatchRequest";
import type { PostPreUploadBatchResponse } from "../types/PostPreUploadBatchResponse";

const getPreUploadBatchUrl = () => {
  return `/api/files/batch`;
};

export const postPreUploadBatch = async (
  batchPreUploadRequest: BatchPreUploadRequest,
  options?: Parameters<typeof orvalApiClient>[1],
): Promise<PostPreUploadBatchResponse> => {
  return orvalApiClient<PostPreUploadBatchResponse>(getPreUploadBatchUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(batchPreUploadRequest),
  });
};
