/**
 * Generated by orval + scripts/restructure-api.ts.
 * Do not edit manually — re-run `pnpm api:generate`.
 */
import { orvalApiClient } from "@/api/orval-mutator";
import type { PostPreUploadRequest as PreUploadRequest } from "../types/PostPreUploadRequest";
import type { PostPreUploadResponse } from "../types/PostPreUploadResponse";

const getPreUploadUrl = () => {
  return `/api/files`;
};

export const postPreUpload = async (
  preUploadRequest: PreUploadRequest,
  options?: Parameters<typeof orvalApiClient>[1],
): Promise<PostPreUploadResponse> => {
  return orvalApiClient<PostPreUploadResponse>(getPreUploadUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(preUploadRequest),
  });
};
