/**
 * Generated by orval + scripts/restructure-api.ts.
 * Do not edit manually — re-run `pnpm api:generate`.
 */
export type PostPreUploadBatchRequest = {
  /** @minItems 1 */
  contentTypes: string[];
};
