/**
 * Generated by orval + scripts/restructure-api.ts.
 * Do not edit manually — re-run `pnpm api:generate`.
 */

import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from "@tanstack/react-query";
import { useMutation } from "@tanstack/react-query";
import type { SecondParameter } from "@/api/common/query-helpers";
import type { BodyType, ErrorType, orvalApiClient } from "@/api/orval-mutator";
import { postSignup1 as signup1 } from "../api/postSignup1";
import type { PostSignup1Request as DevLoginRequest } from "../types/PostSignup1Request";

export const getSignup1MutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof signup1>>,
    TError,
    { data: BodyType<DevLoginRequest> },
    TContext
  >;
  request?: SecondParameter<typeof orvalApiClient>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof signup1>>,
  TError,
  { data: BodyType<DevLoginRequest> },
  TContext
> => {
  const mutationKey = ["signup1"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof signup1>>,
    { data: BodyType<DevLoginRequest> }
  > = (props) => {
    const { data } = props ?? {};

    return signup1(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type Signup1MutationResult = NonNullable<
  Awaited<ReturnType<typeof signup1>>
>;
export type Signup1MutationBody = BodyType<DevLoginRequest>;
export type Signup1MutationError = ErrorType<unknown>;

export const usePostSignup1 = <TError = ErrorType<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof signup1>>,
      TError,
      { data: BodyType<DevLoginRequest> },
      TContext
    >;
    request?: SecondParameter<typeof orvalApiClient>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof signup1>>,
  TError,
  { data: BodyType<DevLoginRequest> },
  TContext
> => {
  return useMutation(getSignup1MutationOptions(options), queryClient);
};
