/**
 * Generated by orval + scripts/restructure-api.ts.
 * Do not edit manually — re-run `pnpm api:generate`.
 */
import type { ArgumentDetailsArgumentType } from "./ArgumentDetailsArgumentType";

export interface ArgumentDetails {
  voicePresignedUrl?: string;
  argumentType?: ArgumentDetailsArgumentType;
}
