/**
 * Generated by orval + scripts/restructure-api.ts.
 * Do not edit manually — re-run `pnpm api:generate`.
 */
export type ArgumentDetailsArgumentType =
  (typeof ArgumentDetailsArgumentType)[keyof typeof ArgumentDetailsArgumentType];

export const ArgumentDetailsArgumentType = {
  OPENING: "OPENING",
  REBUTTAL: "REBUTTAL",
  CONCLUSION: "CONCLUSION",
} as const;
