/**
 * Generated by orval + scripts/restructure-api.ts.
 * Do not edit manually — re-run `pnpm api:generate`.
 */
import type { ArgumentDetails } from "./ArgumentDetails";

export interface DebateUser {
  agreeNickname?: string;
  imagePresignedUrl?: string;
  arguments?: ArgumentDetails[];
}
