/**
 * Generated by orval + scripts/restructure-api.ts.
 * Do not edit manually — re-run `pnpm api:generate`.
 */
import type { FindPollResponseCategoryType } from "./FindPollResponseCategoryType";

export interface FindPollResponse {
  pollId?: number;
  categoryType?: FindPollResponseCategoryType;
  title?: string;
  agreeNickname?: string;
  disagreeNickname?: string;
  voteCount?: number;
}
