/**
 * Generated by orval + scripts/restructure-api.ts.
 * Do not edit manually — re-run `pnpm api:generate`.
 */
export type FindPollDetailsResponseMyAgreementType =
  (typeof FindPollDetailsResponseMyAgreementType)[keyof typeof FindPollDetailsResponseMyAgreementType];

export const FindPollDetailsResponseMyAgreementType = {
  AGREE: "AGREE",
  DISAGREE: "DISAGREE",
} as const;
