/**
 * Generated by orval + scripts/restructure-api.ts.
 * Do not edit manually — re-run `pnpm api:generate`.
 */
import type { CommonResponse } from "@/api/common/types/CommonResponse";
import type { FindPollResponse } from "./FindPollResponse";

export type GetViewResponse = CommonResponse<{
  content?: FindPollResponse[];
  pageNumber?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
  isFirst?: boolean;
  isLast?: boolean;
}>;
