/**
 * Generated by orval + scripts/restructure-api.ts.
 * Do not edit manually — re-run `pnpm api:generate`.
 */
import type { CommonResponse } from "@/api/common/types/CommonResponse";
import type { DebateUser } from "./DebateUser";
import type { FindPollDetailsResponseMyAgreementType } from "./FindPollDetailsResponseMyAgreementType";

export type GetViewDetailsResponse = CommonResponse<{
  title?: string;
  agree?: DebateUser;
  disagree?: DebateUser;
  agreeVoteCount?: number;
  disagreeVoteCount?: number;
  myAgreementType?: FindPollDetailsResponseMyAgreementType;
  expiredAt?: string;
}>;
