/**
 * Generated by orval + scripts/restructure-api.ts.
 * Do not edit manually — re-run `pnpm api:generate`.
 */
export type View1SortType = (typeof View1SortType)[keyof typeof View1SortType];

export const View1SortType = {
  LATEST: "LATEST",
  POPULAR: "POPULAR",
  DEADLINE: "DEADLINE",
} as const;
