/**
 * Generated by orval + scripts/restructure-api.ts.
 * Do not edit manually — re-run `pnpm api:generate`.
 */
export type ViewCategoryType =
  (typeof ViewCategoryType)[keyof typeof ViewCategoryType];

export const ViewCategoryType = {
  ISSUE: "ISSUE",
  LOVE: "LOVE",
  SPORTS: "SPORTS",
  GAME: "GAME",
  CULTURE_TECH: "CULTURE_TECH",
  OTHERS: "OTHERS",
} as const;
