/**
 * Generated by orval + scripts/restructure-api.ts.
 * Do not edit manually — re-run `pnpm api:generate`.
 */
export type View1StatusType =
  (typeof View1StatusType)[keyof typeof View1StatusType];

export const View1StatusType = {
  OPEN: "OPEN",
  CLOSED: "CLOSED",
} as const;
